### ISSUE TITLE
Playlist verschwindet aus Fenster

### ISSUE THREAD

**Issue by Zork80** [Git-J219/musicman#5]
Nach dem Hinzufügen mehrere Lieder zur Playlist wandert diese nach unten aus dem Fenster.
- Das hinzugefügte Album verfügt über kein Bild.

Fenster in normaler Größe:
![Playlist_1](https://user-images.githubusercontent.com/69639535/105714203-58e41e00-5f1c-11eb-9b84-a7594a987df5.png)

Fenster in Höhe maximiert:
![Playlist_2](https://user-images.githubusercontent.com/69639535/105714297-72856580-5f1c-11eb-8425-fd98cdc4044c.png)

**Comment by Git-J219** [comment]
Erstmal: Danke das du mein Programm verwendest.
Ich werde mir den Fehler das die Wiedergabeliste aus dem Fenster geht mal ansehen.
Und für den anderen Fehler bitte ein eigenes Issue erstellen.

**Comment by Git-J219** [comment]
Erstmal: danke das du mein Programm verwendest
Zu dem Fehler das kein Bild angezeigt wird:
Bitte ein eigenes Issue erstellen.

Zum Fehler mit der Playlist und das sie aus dem Fenster geht: hast du die neuste Version?
Der Fehler tritt bei mir nicht auf.
![Fenster bei der kleinsten Größe](https://user-images.githubusercontent.com/64012180/105720638-ef680d80-5f23-11eb-805e-df19805d0f43.png)

**Comment by Git-J219** [comment]
Das Problem wurde mit Version 2.1.12 gelöst

**Comment by Zork80** [comment]
Der Fehler ist auch für mich mit Version 2.1.12 nicht mehr reproduzierbar.

**Comment by Git-J219** [comment]
Danke das du den Fehler gemeldet hast.
